import {Suspense} from 'react';
import {Await, Link} from 'react-router';
import {Script} from '@shopify/hydrogen';
import {Wave} from '~/components/kaizen/Brand';
import {NewsletterForm} from '~/components/kaizen/NewsletterForm';
import {collectionTitle} from '~/lib/text';
import {
  FOGYASZTOBARAT_ID,
  FOGYASZTOBARAT_LOADER,
} from '~/lib/fogyasztobarat';

const BRAND_LINKS = [
  ['A filozófia', '/#filozofia'],
  ['Kaizen Family', '/#family'],
  ['Rólunk', '/#rolunk'],
];

// Used only if the shop has no blog yet.
const FALLBACK_BLOG = {handle: 'hirek', title: 'Hírek'};

// Fogyasztóbarát ("consumer friendly") trust badge. The vendor loader reads
// the widget id from the element with id "fbarat", fetches the badge markup
// and appends a fixed-position HUD to <body>, so where the tag sits in the
// footer doesn't affect placement. Its origin is allow-listed in the CSP in
// app/entry.server.jsx; the ids live in app/lib/fogyasztobarat.js.

// The ÁSZF is generated by Fogyasztóbarát and served from our own route
// (app/routes/pages.aszf.jsx), not from a Shopify policy.
const ASZF_LINK = ['ÁSZF', '/pages/aszf'];

// Used only if the Storefront API returns no policies for the shop.
const FALLBACK_HELP = [
  ['Szállítás', '/policies/shipping-policy'],
  ['Visszaküldés', '/policies/refund-policy'],
  ['Adatkezelés', '/policies/privacy-policy'],
  ASZF_LINK,
];

/**
 * Maps the shop's configured policies onto footer links. Titles are
 * localised here so the footer reads Hungarian even when the policy titles
 * in Shopify are still English.
 * @param {FooterQuery['shop'] | undefined} shop
 */
function helpLinks(shop) {
  if (!shop) return FALLBACK_HELP;
  const entries = [
    ['Szállítás', shop.shippingPolicy],
    ['Visszaküldés', shop.refundPolicy],
    ['Adatkezelés', shop.privacyPolicy],
  ].filter(([, policy]) => policy?.handle);
  if (!entries.length) return FALLBACK_HELP;
  return [
    ...entries.map(([label, policy]) => [
      label,
      `/policies/${policy.handle}`,
    ]),
    ASZF_LINK,
  ];
}

/**
 * KAIZENTYPE footer. Product and policy links come from the deferred
 * footer query; the rest is brand copy.
 * @param {{
 *   footer: Promise<FooterQuery|null>,
 *   navCollections?: Array<{handle: string, title: string}>,
 * }} props
 */
export function KaizenFooter({footer, navCollections = []}) {
  return (
    <>
      <Suspense fallback={<FooterShell collections={navCollections} />}>
        <Await
          resolve={footer}
          errorElement={<FooterShell collections={navCollections} />}
        >
          {(data) => (
            <FooterShell
              collections={navCollections}
              products={data?.products?.nodes ?? []}
              help={helpLinks(data?.shop)}
              blog={data?.blogs?.nodes?.[0] ?? FALLBACK_BLOG}
              articles={data?.articles?.nodes ?? []}
            />
          )}
        </Await>
      </Suspense>
      {/*
        Kept outside the Suspense boundary so the loader is injected once,
        not for both the fallback and the resolved shell. `waitForHydration`
        appends the tag after hydration (no SSR markup, no hydration mismatch)
        and dedupes by src, so StrictMode's double effects are harmless.
      */}
      <Script
        waitForHydration
        src={FOGYASZTOBARAT_LOADER}
        id="fbarat"
        data-id={FOGYASZTOBARAT_ID}
      />
    </>
  );
}

/**
 * @param {{
 *   collections?: Array<{handle: string, title: string}>,
 *   products?: Array<{id: string, handle: string, title: string}>,
 *   help?: Array<[string, string]>,
 *   blog?: {handle: string, title: string},
 *   articles?: Array<{id: string, handle: string, title: string, blog: {handle: string}}>,
 * }} props
 */
function FooterShell({
  collections = [],
  products = [],
  help = FALLBACK_HELP,
  blog = FALLBACK_BLOG,
  articles = [],
}) {
  const privacy = help.find(([label]) => label === 'Adatkezelés')?.[1];
  const terms = help.find(([label]) => label === 'ÁSZF')?.[1];
  return (
    <footer className="ft">
      <div className="ft-brush" aria-hidden="true">
        <Wave shape="edge" fill="var(--ink-red)" />
      </div>
      <div className="ft-grid">
        <div className="ft-brand">
          <Link to="/" className="ft-logo">
            <img
              src="/kaizen-logo.png"
              alt="KaizenType"
              width="190"
              height="190"
            />
          </Link>
          <p className="ft-tag">
            Budapesten készülő, nehéz pamut alapdarabok — és a Kaizen Family
            közösség.
          </p>
        </div>

        <div className="ft-col">
          <span className="ft-h">Vásárlás</span>
          {collections.map((c) => (
            <Link
              to={`/collections/${c.handle}`}
              key={c.handle}
              className="ft-link"
            >
              {collectionTitle(c)}
            </Link>
          ))}
          {products.map((p) => (
            <Link to={`/products/${p.handle}`} key={p.id} className="ft-link">
              {p.title}
            </Link>
          ))}
          <Link to="/collections/all" className="ft-link">
            Összes termék
          </Link>
        </div>

        <div className="ft-col">
          <span className="ft-h">A márka</span>
          {BRAND_LINKS.map(([label, to]) => (
            <Link to={to} key={label} className="ft-link">
              {label}
            </Link>
          ))}
        </div>

        <div className="ft-col">
          <span className="ft-h">Blog</span>
          {articles.map((a) => (
            <Link
              to={`/blogs/${a.blog.handle}/${a.handle}`}
              key={a.id}
              className="ft-link"
            >
              {a.title}
            </Link>
          ))}
          <Link to={`/blogs/${blog.handle}`} className="ft-link">
            Összes bejegyzés
          </Link>
        </div>

        <div className="ft-col">
          <span className="ft-h">Segítség</span>
          {help.map(([label, to]) => (
            <Link to={to} key={label} className="ft-link">
              {label}
            </Link>
          ))}
        </div>

        <div className="ft-news">
          <span className="ft-h">
            <span className="kanji">改善</span> — Hírlevél
          </span>
          <p className="ft-news-p">
            Nem küldünk sok hírlevelet, amit küldünk az igazán hasznos lesz
            számodra.
          </p>
          <NewsletterForm />
        </div>
      </div>

      <div className="ft-base">
        <span>
          © {new Date().getFullYear()} KaizenType — Készült Budapesten
        </span>
        <span className="ft-base-links">
          {privacy ? <Link to={privacy}>Adatkezelés</Link> : null}
          {terms ? <Link to={terms}>ÁSZF</Link> : null}
        </span>
      </div>
    </footer>
  );
}

/** @typedef {import('storefrontapi.generated').FooterQuery} FooterQuery */
