import {Suspense} from 'react';
import {Await, Link} from 'react-router';
import {Script} from '@shopify/hydrogen';
import {Wave} from '~/components/kaizen/Brand';
import {NewsletterForm} from '~/components/kaizen/NewsletterForm';
import {BRAND_TAGLINE, collectionTitle} from '~/lib/text';
import {
  FOGYASZTOBARAT_ID,
  FOGYASZTOBARAT_LOADER,
} from '~/lib/fogyasztobarat';

const BRAND_LINKS = [
  ['A filozófia', '/#filozofia'],
  ['Kaizen Family', '/#family'],
  ['Rólunk', '/#rolunk'],
];

// Used only if the shop has no blog yet.
const FALLBACK_BLOG = {handle: 'hirek', title: 'Hírek'};

// Fogyasztóbarát ("consumer friendly") trust badge. The vendor loader reads
// the widget id from the element with id "fbarat", fetches the badge markup
// and appends a fixed-position HUD to <body>, so where the tag sits in the
// footer doesn't affect placement. Its origin is allow-listed in the CSP in
// app/entry.server.jsx; the ids live in app/lib/fogyasztobarat.js.

// The ÁSZF is generated by Fogyasztóbarát and served from our own route
// (app/routes/pages.aszf.jsx), not from a Shopify policy. It also covers
// shipping and data handling, so those links point at the same page.
const ASZF_PATH = '/pages/aszf';

// Returns go through the contact page for now: the self-serve returns page
// (app/routes/pages.visszakuldes.jsx) is parked in app/routes.js until a
// later release, and the Shopify refund policy is empty and not linked.
const RETURNS_LINK = ['Visszaküldés', '/pages/contact'];

/** The "Segítség" column, in order. */
const HELP_LINKS = [
  ['Szállítás', ASZF_PATH],
  RETURNS_LINK,
  ['Adatkezelés', ASZF_PATH],
  ['ÁSZF', ASZF_PATH],
];

/**
 * KAIZENTYPE footer. Product and blog links come from the deferred footer
 * query; the rest is brand copy.
 * @param {{
 *   footer: Promise<FooterQuery|null>,
 *   navCollections?: Array<{handle: string, title: string}>,
 * }} props
 */
export function KaizenFooter({footer, navCollections = []}) {
  return (
    <>
      <Suspense fallback={<FooterShell collections={navCollections} />}>
        <Await
          resolve={footer}
          errorElement={<FooterShell collections={navCollections} />}
        >
          {(data) => (
            <FooterShell
              collections={navCollections}
              products={data?.products?.nodes ?? []}
              blog={data?.blogs?.nodes?.[0] ?? FALLBACK_BLOG}
              articles={data?.articles?.nodes ?? []}
            />
          )}
        </Await>
      </Suspense>
      {/*
        Kept outside the Suspense boundary so the loader is injected once,
        not for both the fallback and the resolved shell. `waitForHydration`
        appends the tag after hydration (no SSR markup, no hydration mismatch)
        and dedupes by src, so StrictMode's double effects are harmless.
      */}
      <Script
        waitForHydration
        src={FOGYASZTOBARAT_LOADER}
        id="fbarat"
        data-id={FOGYASZTOBARAT_ID}
      />
    </>
  );
}

/**
 * @param {{
 *   collections?: Array<{handle: string, title: string}>,
 *   products?: Array<{id: string, handle: string, title: string}>,
 *   blog?: {handle: string, title: string},
 *   articles?: Array<{id: string, handle: string, title: string, blog: {handle: string}}>,
 * }} props
 */
function FooterShell({
  collections = [],
  products = [],
  blog = FALLBACK_BLOG,
  articles = [],
}) {
  return (
    <footer className="ft">
      <div className="ft-brush" aria-hidden="true">
        <Wave shape="edge" fill="var(--ink-red)" />
      </div>
      <div className="ft-grid">
        <div className="ft-brand">
          <Link to="/" className="ft-logo">
            <img
              src="/kaizen-logo.png"
              alt="KaizenType"
              width="190"
              height="190"
            />
          </Link>
          <p className="ft-tag">{BRAND_TAGLINE}</p>
        </div>

        <div className="ft-col">
          <span className="ft-h">Vásárlás</span>
          {collections.map((c) => (
            <Link
              to={`/collections/${c.handle}`}
              key={c.handle}
              className="ft-link"
            >
              {collectionTitle(c)}
            </Link>
          ))}
          {products.map((p) => (
            <Link to={`/products/${p.handle}`} key={p.id} className="ft-link">
              {p.title}
            </Link>
          ))}
        </div>

        <div className="ft-col">
          <span className="ft-h">A márka</span>
          {BRAND_LINKS.map(([label, to]) => (
            <Link to={to} key={label} className="ft-link">
              {label}
            </Link>
          ))}
        </div>

        <div className="ft-col">
          <span className="ft-h">Blog</span>
          {articles.map((a) => (
            <Link
              to={`/blogs/${a.blog.handle}/${a.handle}`}
              key={a.id}
              className="ft-link"
            >
              {a.title}
            </Link>
          ))}
          <Link to={`/blogs/${blog.handle}`} className="ft-link">
            Összes bejegyzés
          </Link>
        </div>

        <div className="ft-col">
          <span className="ft-h">Segítség</span>
          <Link to="/pages/contact" className="ft-link">
            Kapcsolat
          </Link>
          {HELP_LINKS.map(([label, to]) => (
            <Link to={to} key={label} className="ft-link">
              {label}
            </Link>
          ))}
        </div>

        <div className="ft-news">
          <span className="ft-h">
            <span className="kanji">改善</span> — Hírlevél
          </span>
          <p className="ft-news-p">
            Nem küldünk sok hírlevelet, amit küldünk az igazán hasznos lesz
            számodra.
          </p>
          <NewsletterForm />
        </div>
      </div>

      <div className="ft-base">
        <span>
          © {new Date().getFullYear()} KaizenType — Készült Budapesten
        </span>
        <span className="ft-base-links">
          <Link to={ASZF_PATH}>Adatkezelés</Link>
          <Link to={ASZF_PATH}>ÁSZF</Link>
        </span>
      </div>
    </footer>
  );
}

/** @typedef {import('storefrontapi.generated').FooterQuery} FooterQuery */
